#include<iostream>
#include<conio.h>

void BankName(float,float);          // Bank Name Show => choose bank 

void ATMwork(float,float);

float WithDraw(float,float);           // User own money can withdraw According to some condition;
float Add_Money(float);          // User can Add money in the Own bank;
float Transfer_money(float,float);     // User can transfer money in another user to some condition;
float Lone(float);               // User can Lone for tempary at the ATM for the some days consition;

void Check(float,float);   
void PrintATM(float,float);
void UserPinId(float,float);         // User can check bankdeail and print after all work at the ATM; 

using namespace std;

int main(){
    float money=20570.187;
    float Ormoney=money;
    BankName(money,Ormoney);
    return 0;
}

void BankName(float money,float Ormoney){
    // string Bank_list[5]={"PUNJAB NATIONAL BANK","BANK OF INDIA","INDIAN BANK","SBI","RBI"};
    int choose;float Total_money=15000;
    cout<<"\n\t\t\t\t\t\t\t\t\t-----------------ATM------------\n";
    cout<<"\t\t\t\t\t\t\t\t\t1 : PUNJAB NATIONAL BANK\n";
    cout<<"\t\t\t\t\t\t\t\t\t2 : BANK OF INDIA \n";
    cout<<"\t\t\t\t\t\t\t\t\t3 : INDIAN BANK \n";
    cout<<"\t\t\t\t\t\t\t\t\t4 : SBI\n";
    cout<<"\t\t\t\t\t\t\t\t\t5 : RBI\n";
    cout<<"\t\t\t\t\t\t\t\t\tCHOOSE BANK : \n";
    cout<<"\t\t\t\t\t\t\t\t\t---------------------------------\n\n";
    cout<<"ENTER : ";
    cin>>choose;
    if(choose<6){
    UserPinId(money,Ormoney);
    }else{
        exit(0);
    }
    // BankDetail(Total_money);
}

void ATMwork(float T_Money,float Ormoney){
    int click;float money;
    cout<<"\t\t\t\t\t\t\t\t\t--------------ATM-WORK------------\n";
    cout<<"\t\t\t\t\t\t\t\t\t[1] : Withdraw Money \n";
    cout<<"\t\t\t\t\t\t\t\t\t[2] : Add Money  \n";
    cout<<"\t\t\t\t\t\t\t\t\t[3] : Transfer Money \n";
    cout<<"\t\t\t\t\t\t\t\t\t[4] : Lone Money \n";    
    cout<<"\t\t\t\t\t\t\t\t\t[5] : Check Balance \n";
    cout<<"\t\t\t\t\t\t\t\t\tEXIT for click 0\n";
    cout<<"\t\t\t\t\t\t\t\t\t---------------------------------\n\n";
    cout<<"ENTER : ";
    cin>>click;
    switch(click){
        case 1: money=WithDraw(T_Money,Ormoney);
                Check(money,Ormoney);          //print Change Money after withdraw;
                break;
        case 2: money=Add_Money(T_Money);
                Check(money,Ormoney);          //print Change Money after withdraw;
                break;
        case 3: money=Transfer_money(T_Money,Ormoney);
                Check(money,Ormoney);          //print Change Money after withdraw;
                break;
        case 4: money=Lone(T_Money);
                Check(money,Ormoney);          //print Change Money after withdraw;
                break;
        case 5: PrintATM(T_Money,Ormoney);
                // cout<<money;             //print Change Money after withdraw;
                break;
        case 0: exit(0);            // direct exit from the atm program.
        default:cout<<"\nINVALID INPUT NUMBERS : \n";
                Check(money,Ormoney);          //print Change Money after withdraw;
                // cout<<"[5] : Check Balance \n";
                break;     
    }
}
void PrintATM(float PT_money,float Ormoney){
    cout<<"\t\t\t\t\t\t\t\t\t--------------------RBI-------------\n";
    cout<<"\t\t\t\t\t\t\t\t\tName: Rohit Thakur \n";
    cout<<"\t\t\t\t\t\t\t\t\tAcc no: xxxxxxxxxx3432\n";
    cout<<"\t\t\t\t\t\t\t\t\tMobile no.: xxxxxxxxxx223\n";
    cout<<"\t\t\t\t\t\t\t\t\tAddress no.: village-asdf | Po- adka | pincode:232\n\n";
    cout<<"\t\t\t\t\t\t\t\t\tBefore  Account_Balance =  "<<Ormoney<<"\n\n";
    cout<<"\t\t\t\t\t\t\t\t\tNOW: Total Balance.:"<<PT_money<<"\n";
    cout<<"\t\t\t\t\t\t\t\t\tDate : 12/12/12\n";
    cout<<"\t\t\t\t\t\t\t\t\tgenerated by atm machine : skm\n\n";
    cout<<"\t\t\t\t\t\t\t\t\t-------------------------------------\n";
    // BankName(PT_money,Ormoney);
}


float WithDraw(float PT_money,float Ormoney){         // PT_money: Pass Total Money on the Withdraw function;
    float Mondraw,Ch_Money;              // Mondraw: Money withdraw written in sort ;

    cout<<"HOW MANY WANT WITHDRAW MONEY:   ";
    cin>>Mondraw;
    if(PT_money<=Mondraw){
        cout<<"\nNOT WITHDRAW So, LESS MONEY : try again and add money\n";
        ATMwork(PT_money,Ormoney);
    }
    else{
         Ch_Money=PT_money-Mondraw;
         return Ch_Money;
    }

}


float Add_Money(float PT_money){
    float Monadd,Ch_Money;
    cout<<"\nHOW MANY WANT ADD MONEY IN THE ACCOUNT:  ";
     cin>>Monadd;
    Ch_Money=PT_money+Monadd;
    return Ch_Money;
}


float Transfer_money(float PT_money,float Ormoney){
    float Montrans,Ch_Money;              // Montrans: Money withdraw written in sort ;
    cout<<"HOW MANY WANT TRANSFER MONEY:  ";
    cin>>Montrans;
    if(PT_money<=Montrans){
        cout<<"\nNOT TRANSFER SO, LESS MONEY : try again and add money\n";
        ATMwork(PT_money,Ormoney);
    }
    else{
         Ch_Money=PT_money-Montrans;
        cout<<"SUCCESSFUL TRASNFER MONEY IN THE GIVEN BANK ACCOUNTS \n";
         return Ch_Money;
    }
}


float Lone(float PT_money){
    cout<<"THIS  FEATURE IS NOT ADDED IN OUR ATM SERVICES \n";
    return PT_money;
}


void Check(float PT_money,float Ormoney){
    int check;
    cout<<"\n[1] FOR PRINT YOUR BANK DETAILS : \n";
    cout<<"[0] FOR EXIT FROM THE ATM : \n";
    cin>>check;
    if(check==1){
        PrintATM(PT_money,Ormoney);
    }
    else{
        exit(0);
    }
}
void UserPinId(float PT_money,float Ormoney){
        int Pin=123456,UsPin;
        cout<<"ENTER YOUR PIN-ID :   ";
        cin>>UsPin;
         if(UsPin==0){
                exit(0);
            }
        if(Pin == UsPin){
            ATMwork(PT_money,Ormoney);
        }
        else{
            cout<<"try again: OR EXIT FOR click [0] !\n \n";
            UserPinId(PT_money,Ormoney);       
        }
}
